name: Auto Ship Update
on:
  schedule:
    - cron: "0 0 * * SUN,WED"
  workflow_dispatch:
jobs:
  data_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull & update submodules
        run: |
          git submodule update --init
          git submodule update --remote
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: tsc
      - run: ls
      - run: npm run ships
      - name: Get Current Time
        uses: 1466587594/get-current-time@v1.0.0
        with:
          format: dddd, MMMM Do YYYY
          utcOffset: "+08:00"
        id: current-time
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Ship Update"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "[Auto] Data Update"
          assignees: octo-kumo
          reviewers: octo-kumo
          body: |
            #### Automatic Ship Update `${{ steps.current-time.outputs.formattedTime }}`
            Pull Request ${{ env.PULL_REQUEST_NUMBER }}
            *This pull request is automatically generated by Github Actions*
          labels: data update, automated
      - name: Check outputs
        run: 'echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"'
